### ISSUE TITLE
Effort gets confused by backing property

### ISSUE THREAD

**Issue by OskarKlintrot** [zzzprojects/EntityFramework-Effort#162] opened 2019-01-25 14:20 UTC
I have an entity that looks something like this:

```csharp
[Column("Startdate", TypeName = "Date")]
private DateTime _startdate { get; set; }

[NotMapped]
public LocalDate Startdate
{
    get => LocalDate.FromDateTime(_startdate);
    set => _startdate = value.ToDateTimeUnspecified();
}
```

This works just fine with EF (though projection doesn't work). I try to seed the database using `Effort.DataLoaders.ObjectData` like this:
```csharp
Data.Table<MyEntity>().Add(new MyEntity { Id = 1, Startdate = new NodaTime.LocalDate(2008, 01, 01) });
```

It seems as if Effort tries to assign `LocalDate` directly to `_startdate` when quering `DbContext`, based on the exception:
```
Effort.Exceptions.EffortException: 'Unhandled exception while trying to initialize the content of 'Table<dbo_MyEntity>' table'
```
First inner exception:
```
EffortException: An unhandled exception occurred while trying to assign value 'Tuesday, 1 January 2008' to Property 'Startdatum' of type 'System.DateTime' during entity initialization for table 'Effort.Internal.DbManagement.Schema.TableName'
```
Second inner exception:
```
InvalidCastException: Specified cast is not valid.
```

**Comment by JonathanMagnan** [comment] 2019-01-28 03:47
Hello @OskarKlintrot ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by OskarKlintrot** [comment] 2019-01-28 07:19
Of course, my bad!

https://github.com/OskarKlintrot/effort-backing-properties-bug

**Comment by JonathanMagnan** [comment] 2019-01-28 13:43
Great thank :)

I will assign it to my developer.

**Comment by JonathanMagnan** [comment] 2019-01-28 21:32
Hello @OskarKlintrot ,

My developer looked at it today. What he told me is the `ObjectData` doesn't support property that are not mapped.

One way to do it is creating directly your entity in Entity Framework and use `CreateRestorePoint` and `RollbackToRestorePoint`.

Here is an example:

```csharp
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Effort.DataLoaders;
using Effort.Provider;
using EffortBug.Domain.Entities;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NodaTime;

namespace EffortBug.UnitTests
{
    [TestClass]
    public class AllShouldPass
    { 
        private EffortConnection _dbConnection;

        [TestInitialize]
        public void TestInitialize()
        {
            EffortProviderConfiguration.RegisterProvider(); 

	        _dbConnection = Effort.DbConnectionFactory.CreateTransient();

	        using (var dbContext = new MvpDbContext(_dbConnection, true))
	        {
				// seed all data you need!
		        dbContext.MyEntities.Add(new MyEntity
		        {
			        Id = 1,
			        Name = "Test",
			        Date = new LocalDate(2019, 01, 28)
		        });

		        dbContext.SaveChanges();
	        }


	        _dbConnection.CreateRestorePoint();
		}
		 

		[TestMethod]
        public async Task CountEntities()
        { 
	        using (var dbContext = new MvpDbContext(_dbConnection, true))
	        {
		        _dbConnection.RollbackToRestorePoint(dbContext);
	        }

			var count = 0;

            // Act
            using (var dbContext = new MvpDbContext(_dbConnection, true))
            {
                count = await dbContext.MyEntities
                    .CountAsync();
            }

            // Assert
            Assert.AreEqual(1, count);
        }

        [TestMethod]
        public async Task RetriveDate()
        {

	        using (var dbContext = new MvpDbContext(_dbConnection, true))
	        {
		        _dbConnection.RollbackToRestorePoint(dbContext);
	        }

			MyEntity myEntity = null;

            // Act
            using (var dbContext = new MvpDbContext(_dbConnection, true))
            {
                myEntity = await dbContext.MyEntities
                    .Where(x => x.Id == 1)
                    .SingleAsync();
            }

            // Assert
            Assert.AreEqual(new LocalDate(2019, 01, 28), myEntity.Date);
        }

        [TestMethod]
        [ExpectedException(typeof(NotSupportedException))]
        public async Task NotSupported()
        {

	        using (var dbContext = new MvpDbContext(_dbConnection, true))
			{
				_dbConnection.RollbackToRestorePoint(dbContext);
			}


			// Arrange
			// Act
			using (var dbContext = new MvpDbContext(_dbConnection, true))
            {
                await dbContext.MyEntities
                    .Select(x => x.Date)
                    .SingleAsync();
            }

            // Assert
            // See ExpectedExceptionAttribute
        }
    }
}
```

Let me know if that succesfully answer your question.

**Comment by OskarKlintrot** [comment] 2019-02-05 12:38
That is one way I probably could do it, yes. If it's by design that `ObjectData` should not support not mapped properties then I guess you can close this issue since "It's not a bug, it's a feature" :)

**Comment by JonathanMagnan** [comment] 2019-02-06 03:00
lol ;)

Perhaps in the future, it will work as expected but for now, let say that's by design.

**Closed by JonathanMagnan** 2019-02-06 03:00 UTC
