### ISSUE TITLE
Self referential entity is not saved

### ISSUE THREAD

**Issue by rwahib** [zzzprojects/EntityFramework-Effort#107] opened 2018-04-05 07:31 UTC
Hi I have an Entity has a Foreign Key is pointing to the same Entity primary key  
every time I try to add the record and save change it throw exception

yet the Primary key and the Foreign key are the same, it happen in first record I was adding
any help will be appreciated

**System.Data.Entity.Infrastructure.DbUpdateException occurred
  HResult=0x80131501
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=EntityFramework
  StackTrace:
   

Inner Exception 1:
UpdateException: An error occurred while updating the entries. See the inner exception for details.

Inner Exception 2:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 3:
ForeignKeyViolationException: Foreign key violation [dbo_Unit :: ReportToUnit]. The key value [-1] does not exists in the referenced table [dbo_Unit :: UnitId].. Error code: RelationError**

**Comment by JonathanMagnan** [comment] 2018-04-05 12:16
Hello @rwahib ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by rwahib** [comment] 2018-04-06 05:35
Sure

**Comment by JonathanMagnan** [comment] 2018-04-30 18:41
Hello @rwahib ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-04-30 18:41 UTC
