### ISSUE TITLE
How to avoid ForeignKeyViolationException when partially populating a context

### ISSUE THREAD

**Issue by urig** [zzzprojects/EntityFramework-Effort#73] opened 2017-05-17 12:04 UTC
Hi, 

First off - Many thanks for making Effort available for free. Much appreciated!

My issue is similar to [this question on stackoverflow.com](http://stackoverflow.com/questions/38489414/unenforce-foreign-key-references-in-effort)

In an EF6 Code First setting, I have a `Customer` entity with a 1-to-many relationship with a `Company` entity. I have a `DbContext` dedicated specifically to `Customers` that has a `DbSet<Customer>` (but does not have a `DbSet<Company>`).

When I try to save a new `Customer` instance into Effort (using a persistent `DbConnection`) I get a `ForeignKeyViolationException` (full details below).

I know that if I add a new `Company` instance with the correct id to the context and save it then the exception will go away, but the problem is my context is not supposed to be aware of `Company` entities - It doesn't have a DbSet<Company>.

Is there some way to make Effort (or NMemory) not enforce foreign key constraints?

Thanks,
@urig

> System.Data.Entity.Infrastructure.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
  ----> System.Data.Entity.Core.UpdateException : An error occurred while updating the entries. See the inner exception for details.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> NMemory.Exceptions.ForeignKeyViolationException : Foreign key violation [dbo_Customers :: CompanyId]. The key value [0] does not exists in the referenced table [dbo_Companies :: CompanyID].. Error code: RelationError
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at CustomerRepoTests.GetCustomer(Int32 customerId) in ...CustomerRepoTests.cs:line 28
--UpdateException
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
--TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Effort.Internal.Common.DatabaseReflectionHelper.InsertEntity(ITable table, Object entity, Transaction transaction)
   at Effort.Internal.CommandActions.InsertCommandAction.CreateAndInsertEntity(ITable table, IList`1 memberBindings, Transaction transaction)
   at Effort.Internal.CommandActions.InsertCommandAction.ExecuteDataReader(ActionContext context)
   at Effort.Provider.EffortEntityCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
--ForeignKeyViolationException
   at NMemory.Tables.Relation`4.ValidateEntityCore(TForeign foreign)
   at NMemory.Tables.Relation`4.NMemory.Tables.IRelationInternal.ValidateEntity(Object foreign)
   at NMemory.Execution.ExecutionHelper.ValidateForeignKeys(IList`1 relations, IEnumerable`1 referringEntities)
   at NMemory.Execution.CommandExecutor.ExecuteInsert[T](T entity, IExecutionContext context)
   at NMemory.Tables.DefaultTable`2.InsertCore(TEntity entity, Transaction transaction)
   at Effort.Internal.DbManagement.Engine.ExtendedTable`2.InsertCore(TEntity entity, Transaction transaction)
   at NMemory.Tables.Table`2.Insert(TEntity entity, Transaction transaction)
   at Effort.Internal.Common.DatabaseReflectionHelper.WrapperMethods.InsertEntity[TEntity](ITable`1 table, TEntity entity, Transaction transaction)

**Comment by davonium** [comment] 2017-07-07 14:59
Why not using a DataLoader and have the database preloaded with the company?

**Comment by urig** [comment] 2017-07-13 07:09
@davonium thank you for suggesting [DataLoaders](https://tflamichblog.wordpress.com/2013/01/22/data-loaders-in-effort/). I was not aware of the feature previously. 

I don't, however, much like the idea of having my unit tests depend on (multiple) CSV files. This has a negative impact on the readability of the test code IMO. Still looking for a simple way to programmatically setup my fake DB given the above constraints.

**Comment by urig** [comment] 2017-07-13 16:12
I think I've found what I'm looking for: `ObjectDataLoader` from the [Extra Effort](https://github.com/christophano/Effort.Extra project). Taking it for a spin and will update if it works out.

**Comment by JonathanMagnan** [comment] 2018-09-06 20:36
Hello @urig ,

We will close this request since it looks to works with `Extra Effort`.

We are currently looking if we should take some code from extra to get it back in `Effort` instead. We should contact the owner soon about it.

Let me know if everything was working when you made your test with `Extra Effort`.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Closed by JonathanMagnan** 2018-09-06 20:36 UTC

**Comment by JonathanMagnan** [comment] 2019-01-24 18:32
Hello @JoeShmoel ,

You could try the `ObjectDataLoader`, see following example: https://github.com/zzzprojects/EntityFramework-Effort/blob/master/Main/Source/lab/Effort.Lab.EF6/Form_Request_EffortExtra.cs

Let me know if that's working.

Best Regards,

Jonathan

**Comment by JoeShmoel** [comment] 2019-01-25 12:01
Hi Johnathan, 
Thanks for the suggestion the problem is that we are using mock and a class lib to load static data as required for the unit test and not every test is the same so we are trying to load minimal mocked data.

It occured to me afterwards that perhaps this is actually an entity framework issue rather than effort as I am trying to get to the lowest point possible which is the context and it would still crash here. I assumed that because effort is the provider it would have the ability to not throw the error but perhaps it is entity framework and you cant override it.

**Comment by JonathanMagnan** [comment] 2019-01-25 14:01
> not every test is the same so we are trying to load minimal mocked data

You can have multiple `ObjectDataLoader` and use the right one when creating the connection. I don't see any problem here.
