### ISSUE TITLE
The store type 'smallint' could not be found in the Effort provider manifest

### ISSUE THREAD

**Issue by jimbolla** [zzzprojects/EntityFramework-Effort#104] opened 2018-03-09 17:35 UTC
Our EF Context is generated with EntityFramework Reverse POCO Generator. It has Property mappings that look like:
```
Property(x => x.BaseDirectoryId).HasColumnName(@"BaseDirectoryId").HasColumnType("smallint").IsRequired()
```

When trying to use it with Effort like so:
``` 
using (var connection = DbConnectionFactory.CreatePersistent("test"))
using (var db = new OurAppDb(connection, true))
{
    // ...
}
```

We get: `System.InvalidOperationException The store type 'smallint' could not be found in the Effort provider manifest`

If I manually replace the SQL column types with the .NET types like so:

bigint -> int64
bit -> boolean
char -> string
float -> double
numeric -> decimal
nvarchar -> string
smallint -> int16
tinyint -> bye
uniqueidentifier -> guid
varchar -> string
varchar(max) -> string

Then Effort seems to work. But AFAICT, the underlying database type is the proper value to store in the mappings. Would it be possible to get Effort to support these types?

**Comment by jimbolla** [comment] 2018-03-09 17:47
Would adding types to this file make it work? Is there a better way?

https://github.com/zzzprojects/EntityFramework-Effort/blob/master/Main/Source/Effort/Provider/EffortProviderManifest.xml

**Comment by JonathanMagnan** [comment] 2018-03-11 15:13
Hello @jimbolla ,

Thank you for reporting,

We will try to look at it and see what's hapenning.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-03-12 23:32
Hello @jimbolla ,

The v1.3.3 has been released

Let me know if that work with smallint

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-03-18 15:24
Hello @jimbolla ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by MazurchakVova** [comment] 2018-06-14 12:33
The store type 'nvarchar(max)' could not be found in the Effort provider manifest

**Comment by JonathanMagnan** [comment] 2018-06-14 13:48
Hello @MazurchakVova ,

Thank you for reporting, we will try to add it during the weekend.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by dflippo1** [comment] 2018-06-25 19:39
The store type 'xml' could not be found in the Effort provider manifest

**Comment by JonathanMagnan** [comment] 2018-06-26 01:59
Hello @dflippo1 ,

Thank you for reporting.

My employee is currently adding a lot of additional types, the `xml` has already been included.

He should complete his tests tomorrow, so a release with compatible with this type should soon be available.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-06-27 22:44
Hello @MazurchakVova , @dflippo1 ,

The v1.3.5 has been released

nvarchar(max) and XML has been added with a few more types.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by ssdanylchuk** [comment] 2018-07-23 08:43
Hi, 

Could you please also add support of type **varbinary(MAX)** as we receive error on this. Also could you please double-check types **datetimeoffset** and **bigint**, as we plan to use them also.

Thanks.

**Comment by JonathanMagnan** [comment] 2018-07-24 01:07
Hello @ssdanylchuk ,

If I remember, my developer had some hard time to test `varbinary` due to how the library is made.

However, we will look at it again and check about your other types.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-08-09 00:45
Hello @ssdanylchuk ,

The v1.3.7 has been released.

`varbinary(MAX)` has been added as well as other type missed.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-08-23 04:54
Hello,

We will close this issue since we believe we address them all.

If we missed one, feel free to create a new issue with it.

Best Regards,

Jonathan

**Closed by JonathanMagnan** 2018-08-23 04:54 UTC

**Comment by Anvar28** [comment] 2019-09-02 11:50
The store type 'VARCHAR' could not be found in the Effort provider manifest

**Comment by JonathanMagnan** [comment] 2019-09-03 13:35
Hello @Anvar28 ,

Could you provide a project with this issue? The `varchar` is the first element in the manifest so I believe we are missing something to reproduce it.

You can send private code here info@zzzprojects.com

Best Regards,

Jonathan

**Comment by JACB91** [comment] 2022-03-28 23:14
Hi I hope you're doing well, could you help me with this issue please The store type 'Clob' could not be found in the Effort provider manifest
