### ISSUE TITLE
Error when creating DB schema with composite primary key

### ISSUE THREAD

**Issue by rolphes** [zzzprojects/EntityFramework-Effort#110] opened 2018-04-27 09:58 UTC
I try to mock a large DB model with Effort. During the creation of the DB scheme (Effort.EntityConnectionFactory.CreateTransient) an error is thrown with the error message: _InvalidOperationException: There is no coersion operator defined between the System.Int64 and System.String types_. I've debugged this error to find out if there is somewhere a type missmatch in the data model.

What I found out is that this error is caused by two tables which are linked with a composite primary key (pk fields are: EntranceId, ServiceType, DiversionId). The data types of of the primary key fields are long, string and string. Inside the method Configure (class RelationConfiguration) two IKeyInfo objects are created with the two primary keys. This is done with a call to RelationConfiguration.EnsureKey -> here a tuple is created with the pk members and its datatypes. Unfortunately this methods generates two different tuples for the two composite primary keys. On tuple with the type Tuple<string,string,long> and the other with the type Tuple<long,string,string>. I guess this is why the above mentiond exception is thrown from the method CreateConverter (class RelationConfiguration).

Any hint to workaround this problem or a fix would be highly appreciated. Thx!

**Here is the complete callstack:**

System.Reflection.TargetInvocationException : Ein Aufrufziel hat einen Ausnahmefehler verursacht.
  ----> System.InvalidOperationException : Zwischen den Typen "System.Int64" und "System.String" ist kein Koersionsoperator definiert.
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei Effort.Internal.DbManagement.Schema.Configuration.RelationConfiguration.CreateConverter(MethodInfo converterMethod, IKeyInfo primaryKeyInfo, IKeyInfo foreignKeyInfo, IRelationContraint[] relationConstraints)
   bei Effort.Internal.DbManagement.Schema.Configuration.RelationConfiguration.Configure(AssociationInfo associationInfo, DbSchemaBuilder builder)
   bei Effort.Internal.DbManagement.Schema.Configuration.RelationConfigurationGroup.Configure(AssociationInfo associationInfo, DbSchemaBuilder builder)
   bei Effort.Internal.DbManagement.Schema.DbSchemaFactory.CreateDbSchema(StoreItemCollection edmStoreSchema)
   bei Effort.Internal.DbManagement.DbContainer.<Initialize>b__0(StoreItemCollection sic)
   bei Effort.Internal.Caching.DbSchemaStore.<>c__DisplayClass1.<GetDbSchema>b__0()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei Effort.Internal.Caching.ConcurrentCache`2.Get(TKey key, Func`1 factory)
   bei Effort.Internal.Caching.DbSchemaStore.GetDbSchema(StoreItemCollection metadata, Func`2 schemaFactoryMethod)
   bei Effort.Internal.DbManagement.DbContainer.Initialize(StoreItemCollection edmStoreSchema)
   bei Effort.Provider.EffortProviderServices.<>c__DisplayClass4.<DbCreateDatabase>b__3(DbConnection x)
   bei Effort.Provider.EffortProviderServices.Wrap[T](DbConnection connection, Func`2 action)
   bei Effort.Provider.EffortProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   bei System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   bei System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   bei Effort.EntityConnectionFactory.CreateEntityConnection(MetadataWorkspace metadata, DbConnection connection)
   bei Effort.EntityConnectionFactory.CreateTransient(String entityConnectionString, IDataLoader dataLoader)
   bei Effort.EntityConnectionFactory.CreateTransient(String entityConnectionString)
   bei Hexagon.SI.CH.Cad.Utils.CadEntities.CadContextTests.Test() in D:\Hexagon.SI.CH.Cad.Utils\Hexagon.SI.CH.Cad.Utils.Tests\CadEntities\CadContextTests.cs:Zeile 12.
--InvalidOperationException
   bei System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   bei System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   bei NMemory.Common.KeyExpressionHelper.CreateKeyConversionExpression(Expression source, MemberInfo[] toMembers, Int32[] mapping, IKeyInfoHelper from, IKeyInfoHelper to)
   bei NMemory.Tables.RelationKeyConverterFactory.CreateConversion[TFrom,TTo](IKeyInfo`1 fromKeyInfo, IKeyInfo`1 toKeyInfo, Int32[] mapping)
   bei NMemory.Tables.RelationKeyConverterFactory.CreatePrimaryToForeignConverter[TPrimaryKey,TForeignKey](IKeyInfo`1 primaryKey, IKeyInfo`1 foreignKey, IRelationContraint[] constraints)

**Comment by JonathanMagnan** [comment] 2018-04-27 11:45
Hello @rolphes ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by rolphes** [comment] 2018-04-27 20:30
Hi Jonathan

Thanks for your feedback. The framework I'm trying to mock is a third party library from a commercial product. So I cannot submit you an example project with this referenced assemblies. But I hope I can extract the relevant parts into a project where the error can be reproduced.

Regards,
Rolf

**Comment by rolphes** [comment] 2018-05-03 20:30
Hi Jonathan

Finally I was able to isolate and reproduce the bug in a simple test project with three related entities (see attachment [EffortTestCompositeKeys.zip](https://github.com/zzzprojects/EntityFramework-Effort/files/1972418/EffortTestCompositeKeys.zip)). To reproduce the bug just build the project and execute the contained unit test "CreatingEffortConnectionForCompositeKeysShouldWork".

Since I forked the source code from GitHub I could actually find the reason for the bug. But first lets hav a look at the db scheema of the test entities:
![compositekeys](https://user-images.githubusercontent.com/16646537/39599512-560c71ea-4f1c-11e8-926c-5a411860cd5b.png)

The entity "EntranceServiceDiversion" has a composite primary key built form three properties and has a relation with the entity "EntranceServiceDiversionHis". Additionally the entity "FacilityAuditLog" is referenced with the same entity with its primary key (ChangeId). So the entity "EntranceServiceDiversionHis" has a composite key built from four properties. 
A consequence of this constellation is that the IKeyInfo is generated in two different ways:
- One time with the  method tableBuilder.FindKey -> here the properties are ordered alphabetically by name to create the tuple
- One time with the method CreateKeyInfo -> here the properties are not ordered
This different implementations lead to the described bug

One important aspect of this issue is that the properties building the referntial constraint in the CSLD and SSDL definitions must not be in alphabetical order -> otherwise the bug cannot be reproduced. I realized that the model designer from Visual Studio 2017 will reorder this properties when the db schema is recreated. So I had to manually change the order of the properties to produce the error. But this bug is still crucial because it also occource with the used third party libray where I cannot change the order of the properties.

![ssdl_compositekeys](https://user-images.githubusercontent.com/16646537/39600392-e42693f0-4f1e-11e8-9d1b-c9aa2a8d04b3.png)

I guess fixing this bug shouldn't be that hard. I was able to temporary fix the problem on my fork by ordering the members in the method EnsureKey. 


           `  if (keyInfo == null)
            {
                members = members.OrderBy(m => m.Name).ToArray();
                keyInfo = KeyInfoHelper.CreateKeyInfo(tableBuilder.EntityType, members);
                tableBuilder.AddKey(keyInfo, unique);
            }`

 I hope that you can reproduce and fix this issue soon. Just ask if you have any questions.

Best regards,
Rolf

**Comment by JonathanMagnan** [comment] 2018-05-04 14:51
Thank a lot @rolphes ,

We will add the request to our to-do list for the next week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-05-08 03:10
Hello @rolphes ,

Just to let you know that we started to investigate the issue.

We discovered there is one major problem for the composite key with different type since some expression built doesn't have the right type order.

We started to fix it in some methods but we found out that the issue is in multiple methods.

We will continue to check it but it seems the issue is bigger than we first thought.

Best Regards,

Jonathan

**Comment by rolphes** [comment] 2018-06-01 13:09
Any news concerning this issue?

**Comment by JonathanMagnan** [comment] 2018-09-27 20:01
Hello @rolphes ,

Sorry for the very big delay,

The v1.3.10 has been released which should fix this issue.

If you have the chance to test it again, let me know if that works correctly.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-10-01 13:29
Great ;)

**Closed by JonathanMagnan** 2018-10-01 13:29 UTC
