### ISSUE TITLE
Transaction Timeout on a query with join

### ISSUE THREAD

**Issue by KodaPOwER** [zzzprojects/EntityFramework-Effort#103] opened 2018-03-07 15:55 UTC
Hello, 
given this piece of code:

Dim _dc =  ObjectContextFactory.CreateTransient<GAREEntities>(loader);

dim conversioni = (From p In _dc.MA_PRODOTTI.Include("MA_DOSAGGIO")
Join conv In _dc.MA_CONVERSIONE On conv.UM_DEST Equals p.MA_DOSAGGIO.UM
Where conv.UM_ORIG = um And p.ID = idProdotto
Select conv.MOLTIPLICATORE, p.MA_DOSAGGIO.Q).FirstOrDefault 

After some minutes of waiting  while executing the query the transaction timeout exception is thrown.

All the other query (all without join) work like a charm and even this if I remove the join, so the problem is on that piece of code.

What is the problem? I've hit a bug?
Thanks

**Comment by JonathanMagnan** [comment] 2018-03-07 19:11
Hello @KodaPOwER ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by KodaPOwER** [comment] 2018-03-08 08:28
Ok,
i will try to set up an example project to upload.

**Comment by KodaPOwER** [comment] 2018-03-08 10:56
@JonathanMagnan 
I have the example ready, can you give me a place where i can upload it or an email where I can send the link. There is some sensitive data inside (our db structure for example) that for NDA i can't release in public.
Thanks,
Simone

**Comment by JonathanMagnan** [comment] 2018-03-08 13:22
Hello @KodaPOwER ,

You can send it here: info@zzzprojects.com or upload it anywhere you want and share the link to our email.

Best Regards,

Jonathan

**Comment by KodaPOwER** [comment] 2018-03-08 13:40
@JonathanMagnan you have mail ;-)

**Comment by JonathanMagnan** [comment] 2018-03-08 13:41
Thank ;)

I will try to have my developer look at it today or tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2018-03-09 17:06
Hello @KodaPOwER ,

We looked at this issue today and it seems to be caused because of your keys which is not from the main entity you use.

For example:

```csharp
var conversione = list1
    .Join(_dc.MA_CONVERSIONE,
        x => x.UM,
        x => x.UM_DEST,
        (maprodotti, maconversione) => new {maconversione, maprodotti}).ToList();
```

is very fast!

However, if MA_DOSAGGIO.UM is used as the key, there is some stuff used internally in the library which makes the query very slow because the `MA_DOSAGGIO` is included also in the query plan.

I'm not sure if you can change your query a little bit but unfortunately, there is nothing we can do at this moment about it.

Best Regards,

Jonathan

**Comment by KodaPOwER** [comment] 2018-03-10 13:45
Hello @JonathanMagnan,
that make sense, I've asked because that query is very fast executed on MS SQL server.
Monday when i will in office i'll try to modify the query if possible and return back.
Can you give some hint on how to diagnose this kind of problem, related to memory db instead to a bug? That's help me and maybe others to filter at source some issue requests.
And as side question, we use your bulk EF framework, it's that compatible with this library? I haven't tried to test function that use that library.
Thanks for your time again.

**Comment by JonathanMagnan** [comment] 2018-03-10 19:41
Hello @KodaPOwER ,

> Can you give some hint on how to diagnose this kind of problem, related to memory db instead to a bug? 

Honestly, we are still new with `Effort` (We didn't create it, only support it) so I'm not sure if I can answer this question correctly ;)

On our side, we just added code source of `Effort` and `NMemory` in your project to check what was happening and played with your query.

The following `foreach` was taking a LOT of time https://github.com/zzzprojects/nmemory/blob/master/Main/Source/NMemory/Execution/CommandExecutor.cs#L87

If I remember, it was creating around 1k entities per seconds which is very slow.

I'm not sure if that help but this is where the issue is.

> And as side question, we use your bulk EF framework, it's that compatible with this library

No that's not compatible yet with this library.

Best Regards,

Jonathan

**Comment by KodaPOwER** [comment] 2018-03-10 23:47
Yep, it helps, @JonathanMagnan thank you. I will download the source code and use it to diagnose other problem that can eventually pop up and maybe elaborate some workaround in our test cases if possible!
I think we can close this issue, i had all answers to my questions.
Thank you for your support!

**Closed** 2018-03-11 15:07 UTC
